"""initial schema

Revision ID: add5f11b634a
Revises: 
Create Date: 2026-03-27 20:11:11.680761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add5f11b634a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=10), nullable=False, comment='aws | azure | gcp'),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('composite_score', sa.Integer(), nullable=False, comment='0 – 100'),
    sa.Column('signal_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Per-source weighted contributions'),
    sa.Column('tier', sa.String(length=20), nullable=False, comment='NORMAL | WATCH | WARNING | CRITICAL'),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'computed_at')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False, comment='eonet | noaa | usgs | gdelt | newsapi | aws_health | azure_health | gcp_health | cloudflare'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='natural_disaster | geopolitical | cyber | infrastructure'),
    sa.Column('region', sa.String(length=50), nullable=False, comment='AWS region (us-east-1) or ISO country code'),
    sa.Column('severity', sa.Float(), nullable=False, comment='0.0 – 1.0'),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_team', sa.String(length=100), nullable=False),
    sa.Column('current_provider', sa.String(length=10), nullable=False, comment='aws | azure | gcp'),
    sa.Column('current_region', sa.String(length=50), nullable=False),
    sa.Column('latency_sensitivity', sa.String(length=10), nullable=False, comment='low | medium | high'),
    sa.Column('cost_tier', sa.String(length=20), nullable=False, comment='standard | optimized | critical'),
    sa.Column('compliance_region', sa.String(length=50), nullable=True),
    sa.Column('monthly_cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migration_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workload_id', sa.UUID(), nullable=False),
    sa.Column('from_provider', sa.String(length=10), nullable=False),
    sa.Column('from_region', sa.String(length=50), nullable=False),
    sa.Column('to_provider', sa.String(length=10), nullable=False),
    sa.Column('to_region', sa.String(length=50), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=False, comment="simulation_id as string or 'manual'"),
    sa.Column('status', sa.String(length=20), nullable=False, comment='recommended | approved | executed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workload_id'], ['workloads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trigger_event_id', sa.UUID(), nullable=False),
    sa.Column('affected_workloads', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_migrations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_cost_delta_usd', sa.Float(), nullable=False),
    sa.Column('resilience_score_before', sa.Integer(), nullable=False),
    sa.Column('resilience_score_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['risk_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # ── TimescaleDB: convert region_risk_scores to a hypertable ──
    op.execute(
        "SELECT create_hypertable('region_risk_scores', 'computed_at', "
        "migrate_data => true, if_not_exists => true);"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_results')
    op.drop_table('migration_logs')
    op.drop_table('workloads')
    op.drop_table('risk_events')
    op.drop_table('region_risk_scores')
    # ### end Alembic commands ###
